import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import weaponsData from "@/data/weapons.json";
import WeaponImage from "@/components/weapons/WeaponImage";
import { getWeaponImageUrlByName } from "@/components/weapons/WeaponUtils";
import { Weapon } from "@/types/Weapon";
import { EntityStats } from "@/types/EntityStats";
import Stats from "@/components/stats/Stats";
import { useState } from "react";
import Level from "@/components/level/Level";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const getWeapons: () => Weapon[] = () => {
  return Object.values(weaponsData as Record<string, Weapon>);
};

export default function Home() {
  const [level, setLevel] = useState<number>(1);
  // Convert the weapons object to a typed array
  const weapons: Weapon[] = getWeapons();

  // Example usage: Get first 5 weapons
  const firstFiveWeapons = weapons.slice(0, 5);

  // Example: Find a specific weapon by name
  const pistol = weapons.find((weapon) => weapon.name === "pistol");

  const capital = (level - 1) * 5 + 50;

  const baseStats: EntityStats = {
    life: 100 + (level - 1) * 3,
    strength: 0,
    wisdom: 0,
    agility: 0,
    resistance: 0,
    science: 0,
    magic: 0,
    frequency: 100,
    cores: 1,
    ram: 6,
    tp: 10,
    mp: 3,
  };

  const investedStats: EntityStats = {
    life: 200,
    strength: 0,
    wisdom: 0,
    agility: 0,
    resistance: 0,
    science: 0,
    magic: 0,
    frequency: 0,
    cores: 0,
    ram: 0,
    tp: 0,
    mp: 0,
  };

  const bonusStats: EntityStats = {
    life: 0,
    strength: 0,
    wisdom: 100,
    agility: 0,
    resistance: 0,
    science: 0,
    magic: 0,
    frequency: 0,
    cores: 0,
    ram: 0,
    tp: 0,
    mp: 0,
  };

  return (
    <>
      <Head>
        <title>Restator Remastered</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Level level={level} setLevel={setLevel} />
          <Stats
            base={baseStats}
            invested={investedStats}
            bonus={bonusStats}
            capital={capital}
          />

          <WeaponImage weaponName="gazor" />

          {/* Display weapons array info */}
          <div
            style={{
              marginTop: "20px",
              padding: "20px",
              border: "1px solid #ccc",
            }}
          >
            <h3>Weapons Data:</h3>
            <p>Total weapons: {weapons.length}</p>
            {pistol && (
              <div>
                <h4>Found Pistol:</h4>
                <p>ID: {pistol.id}</p>
                <p>Name: {pistol.name}</p>
                <p>
                  <img
                    src={getWeaponImageUrlByName(pistol.name)}
                    alt={pistol.name}
                  />
                </p>
                <p>Level: {pistol.level}</p>
                <p>Cost: {pistol.cost}</p>
                <p>Max Range: {pistol.max_range}</p>
                <p>Effects: {pistol.effects.length}</p>
                <p>Passive Effects: {pistol.passive_effects.length}</p>
              </div>
            )}

            <h4>First 5 Weapons:</h4>
            <ul>
              {firstFiveWeapons.map((weapon) => (
                <li key={weapon.id}>
                  {weapon.name} (ID: {weapon.id}, Level: {weapon.level})
                </li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </>
  );
}
