import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import weaponsData from "@/data/weapons.json";
import WeaponImage from "@/components/weapons/WeaponImage";
import { getWeaponImageUrlByName } from "@/components/weapons/WeaponUtils";
import { Weapon } from "@/types/Weapon";
import { EntityStats } from "@/types/EntityStats";
import Stats from "@/components/stats/Stats";
import { useMemo, useState } from "react";
import { EMPTY_STATS } from "@/constants/Stats.constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const getWeapons: () => Weapon[] = () => {
  return Object.values(weaponsData as Record<string, Weapon>);
};

export default function Home() {
  const [level, setLevel] = useState<number>(1);
  const [investedStats, setInvestedStats] = useState<EntityStats>(EMPTY_STATS);
  const [investedCapital, setInvestedCapital] = useState<number>(0);

  // Convert the weapons object to a typed array
  const weapons: Weapon[] = getWeapons();

  // Example usage: Get first 5 weapons
  const firstFiveWeapons = weapons.slice(0, 5);

  // Example: Find a specific weapon by name
  const pistol = weapons.find((weapon) => weapon.name === "pistol");

  const totalCapital = useMemo(() => {
    return (
      50 +
      5 * (level - 1) +
      Math.floor(level / 100) * 45 +
      Math.floor((level - 1) / 300) * 95
    );
  }, [level]);

  const baseStats: EntityStats = {
    life: 100 + (level - 1) * 3,
    strength: 0,
    wisdom: 0,
    agility: 0,
    resistance: 0,
    science: 0,
    magic: 0,
    frequency: 100,
    cores: 1,
    ram: 6,
    tp: 10,
    mp: 3,
  };

  const bonusStats: EntityStats = {
    life: 0,
    strength: 0,
    wisdom: 100,
    agility: 0,
    resistance: 0,
    science: 0,
    magic: 0,
    frequency: 0,
    cores: 0,
    ram: 0,
    tp: 0,
    mp: 0,
  };

  const totalStats: EntityStats = {
    life: baseStats.life + investedStats.life + bonusStats.life,
    strength: baseStats.strength + investedStats.strength + bonusStats.strength,
    wisdom: baseStats.wisdom + investedStats.wisdom + bonusStats.wisdom,
    agility: baseStats.agility + investedStats.agility + bonusStats.agility,
    resistance:
      baseStats.resistance + investedStats.resistance + bonusStats.resistance,
    science: baseStats.science + investedStats.science + bonusStats.science,
    magic: baseStats.magic + investedStats.magic + bonusStats.magic,
    frequency:
      baseStats.frequency + investedStats.frequency + bonusStats.frequency,
    cores: baseStats.cores + investedStats.cores + bonusStats.cores,
    ram: baseStats.ram + investedStats.ram + bonusStats.ram,
    tp: baseStats.tp + investedStats.tp + bonusStats.tp,
    mp: baseStats.mp + investedStats.mp + bonusStats.mp,
  };

  const onInvestedCapitalChange = (
    newInvested: EntityStats,
    investedCapital: number
  ) => {
    setInvestedCapital(investedCapital);
    setInvestedStats(newInvested);
  };

  return (
    <>
      <Head>
        <title>Restator Remastered</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Stats
            baseStats={baseStats}
            investedStats={investedStats}
            bonusStats={bonusStats}
            totalStats={totalStats}
            totalCapital={totalCapital}
            investedCapital={investedCapital}
            level={level}
            setLevel={setLevel}
            onInvestedCapitalChange={onInvestedCapitalChange}
          />

          <WeaponImage weaponName="gazor" />

          {/* Display weapons array info */}
          <div
            style={{
              marginTop: "20px",
              padding: "20px",
              border: "1px solid #ccc",
            }}
          >
            <h3>Weapons Data:</h3>
            <p>Total weapons: {weapons.length}</p>
            {pistol && (
              <div>
                <h4>Found Pistol:</h4>
                <p>ID: {pistol.id}</p>
                <p>Name: {pistol.name}</p>
                <p>
                  <img
                    src={getWeaponImageUrlByName(pistol.name)}
                    alt={pistol.name}
                  />
                </p>
                <p>Level: {pistol.level}</p>
                <p>Cost: {pistol.cost}</p>
                <p>Max Range: {pistol.max_range}</p>
                <p>Effects: {pistol.effects.length}</p>
                <p>Passive Effects: {pistol.passive_effects.length}</p>
              </div>
            )}

            <h4>First 5 Weapons:</h4>
            <ul>
              {firstFiveWeapons.map((weapon) => (
                <li key={weapon.id}>
                  {weapon.name} (ID: {weapon.id}, Level: {weapon.level})
                </li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </>
  );
}
